### ISSUE TITLE
ignore input when camera is not current

### ISSUE THREAD

**Issue by Qubus0** [MarcPhi/godot-free-look-camera#1]
I was using your very neat camera to debug a scene with a fixed camera. After debugging, I just left it in the scene.
Then I noticed that every right click moved the mouse to the middle of the screen. Turns out it came from the free look camera although it was not active.

Adding this to the script resolved the issue
```gdscript
func _input(event):
	if not current:
		return
```

**Comment by MarcPhi** [comment]
Thanks for the report.

Implemented in 5cac2ac
